spring:
  application:
    name: hackathon

  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://ep-raspy-recipe-atqijvob-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslMode=REQUIRE&options=endpoint%3Dep-raspy-recipe-atqijvob-pooler}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_hnOzsiu2Rxg5}
    pool:
      validation-query: "SELECT 1"


  sql:
    init:
      mode: always

server:

  port: ${PORT:8090}

logging:
  level:
    vallegrande.edu.pe: INFO
    org.springframework.r2dbc: DEBUG