apiVersion: v1
kind: Service
metadata:
  name: junior-vicente-43-service
  namespace: junior-vicente-43-namespace
  labels:
    app: vehiculo-app
spec:
  selector:
    app: vehiculo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090