apiVersion: v1
kind: Secret
metadata:
  name: junior-vicente-43-secret
  namespace: junior-vicente-43-namespace
  labels:
    app: vehiculo-app
type: Opaque
data:
  # PUERTO FLEXIBLE para la app en base64 ("9090")
  PUERTO_FLEXIBLE: OTA5MA==
  username: YWRtaW4=
  password: UGFzc3dvcmQxMQ==