apiVersion: apps/v1
kind: Deployment
metadata:
  name: junior-vicente-43-deployment
  namespace: junior-vicente-43-namespace
  labels:
    app: vehiculo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vehiculo-app
  template:
    metadata:
      labels:
        app: vehiculo-app
    spec:
      containers:
        - name: vehiculo-app
          image: llampier2/ht-241-43-junior-vicente:latest
          ports:
            - containerPort: 9090
          env:
          
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: junior-vicente-43-secret
                  key: PUERTO_FLEXIBLE
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: junior-vicente-43-config
                  key: APP_ENV
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: junior-vicente-43-config
                  key: APP_VERSION
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: junior-vicente-43-config
                  key: APP_PORT
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: junior-vicente-43-secret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: junior-vicente-43-secret
                  key: password