apiVersion: v1
kind: Service
metadata:
  name: ms-alquiler-service
  namespace: hct-alquiler-junior-vicente
spec:
  selector:
    app: ms-alquiler
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: ClusterIP
