apiVersion: v1
kind: Secret
metadata:
  name: ms-alquiler-secret
  namespace: hct-alquiler-junior-vicente
type: Opaque
stringData:
  DB_URL: "r2dbc:postgresql://neondb_owner:npg_WOMVX3CPR9or@ep-wandering-queen-ah3hgnf2-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=REQUIRE"
  DB_USERNAME: "neondb_owner"
  DB_PASSWORD: "npg_WOMVX3CPR9or"
