apiVersion: v1
kind: Secret
metadata:
  name: ms-cliente-secret
  namespace: hct-cliente-junior-vicente
type: Opaque
stringData:
  DB_URL: "r2dbc:postgresql://neondb_owner:npg_Ph47WKytBxeL@ep-polished-salad-atllrhaj-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=REQUIRE"
  DB_USERNAME: "neondb_owner"
  DB_PASSWORD: "npg_Ph47WKytBxeL"
